name: CI/CD - Asset Manager

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      # Local runner veya containerda kullanýlacak environment
      APP_PORT: ${{ secrets.APP_PORT }}
      STUDENT_NAME: ${{ secrets.STUDENT_NAME }}
      ASPNETCORE_ENVIRONMENT: Production
      Jwt__Key: ${{ secrets.Jwt__Key }}
      Jwt__Issuer: ${{ secrets.Jwt__Issuer }}
      Jwt__Audience: ${{ secrets.Jwt__Audience }}
      Jwt__DurationInMinutes: ${{ secrets.Jwt__DurationInMinutes }}
      MSSQL_SA_PASSWORD: ${{ secrets.MSSQL_SA_PASSWORD }}
      ConnectionStrings__DefaultConnection: ${{ secrets.ConnectionStrings__DefaultConnection }}

    steps:
      # 1.Repo’yu checkout et
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. NET SDK Kur
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '10.0.x'

      # 3. Restore dependencies
      - name: Restore dependencies
        run: dotnet restore AssetManager.slnx

      # 4. Build solution
      - name: Build solution
        run: dotnet build AssetManager.slnx --configuration Release --no-restore

      # 5. Run tests
      - name: Run Tests
        run: dotnet test AssetManager.slnx --configuration Release --verbosity normal

      # 6. Package Docker images
      - name: Build Docker images
        run: docker compose -f compose.yml build --pull

      # 7. Deploy to remote server via SSH
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }} # Þifre kullansaydýk password: ${{ secrets.VPS_PASSWORD }} olacaktý
          port: 22
          script: |
            cd ${{ secrets.DEPLOY_PATH }}
            git pull origin main

            # Sunucuda .env dosyasýný oluþtur (Deðiþkenlerin Docker'a geçmesini saðlar)
            echo "APP_PORT=${{ secrets.APP_PORT }}" > .env
            echo "STUDENT_NAME=${{ secrets.STUDENT_NAME }}" >> .env
            echo "ASPNETCORE_ENVIRONMENT=Production" >> .env
            echo "MSSQL_SA_PASSWORD=${{ secrets.MSSQL_SA_PASSWORD }}" >> .env
            echo "ConnectionStrings__DefaultConnection=${{ secrets.ConnectionStrings__DefaultConnection }}" >> .env
            echo "Jwt__Key=${{ secrets.Jwt__Key }}" >> .env
            echo "Jwt__Issuer=${{ secrets.Jwt__Issuer }}" >> .env
            echo "Jwt__Audience=${{ secrets.Jwt__Audience }}" >> .env
            echo "Jwt__DurationInMinutes=${{ secrets.Jwt__DurationInMinutes }}" >> .env

            # Build iþlemini sunucu üzerinde yapalým (Docker Hub kullanmadýðýmýz için)
            docker compose down
            docker compose up -d --build --remove-orphans
